/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.archstudio.xadl3.hints_3_0.validation;

import org.archstudio.xadl3.hints_3_0.Value;

/**
 * A sample validator interface for {@link org.archstudio.xadl3.hints_3_0.Hint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HintValidator
{
  boolean validate();

  boolean validateValue(Value value);
  boolean validateName(String value);
}
