/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.archstudio.xadl3.implementation_3_0.validation;


/**
 * A sample validator interface for {@link org.archstudio.xadl3.implementation_3_0.Implementation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImplementationValidator
{
  boolean validate();

  boolean validateId(String value);
}
