/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.archstudio.xadl3.structure_3_0.validation;

import org.archstudio.xadl3.structure_3_0.InterfaceMapping;
import org.archstudio.xadl3.structure_3_0.Structure;

import org.archstudio.xadl3.xadlcore_3_0.Extension;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.archstudio.xadl3.structure_3_0.SubStructure}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubStructureValidator
{
  boolean validate();

  boolean validateInnerStructureLink(Structure value);
  boolean validateInterfaceMapping(EList<InterfaceMapping> value);
  boolean validateExt(EList<Extension> value);
  boolean validateId(String value);
}
