/*
 * generated by Xtext
 */
package org.archstudio.prolog.xtext;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PrologRuntimeModule extends org.archstudio.prolog.xtext.AbstractPrologRuntimeModule {

}
