package org.archstudio.bna.things.swt;

import org.archstudio.bna.IBNAView;
import org.archstudio.bna.ICoordinateMapper;
import org.archstudio.bna.IThingPeer;
import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.IThingRefKey;
import org.archstudio.bna.keys.ThingKey;
import org.archstudio.bna.keys.ThingRefKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.things.swt]/Thing[name=SWTScrollBar].
 */
 
@SuppressWarnings("all")
@NonNullByDefault
public abstract class SWTScrollBarThingBase extends org.archstudio.bna.things.swt.AbstractControlThing
	implements org.archstudio.bna.IThing {

	public static final IThingKey<java.lang.Integer> MAX_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("max", SWTScrollBarThingBase.class));

	public static final IThingKey<java.lang.Integer> MIN_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("min", SWTScrollBarThingBase.class));

	public static final IThingKey<org.archstudio.bna.things.swt.SWTScrollBarThing.Type> TYPE_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("type", SWTScrollBarThingBase.class));

	public static final IThingKey<java.lang.Integer> VALUE_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("value", SWTScrollBarThingBase.class));

	public SWTScrollBarThingBase(@Nullable Object id) {
		super(id);
	}

	@Override
	public IThingPeer<? extends SWTScrollBarThing> createPeer(IBNAView view, ICoordinateMapper cm) {
		return new SWTScrollBarThingPeer<>((SWTScrollBarThing)this, view, cm);
	}

	@Override
	protected void initProperties() {
		initProperty(org.archstudio.bna.things.swt.SWTScrollBarThing.MAX_KEY, 100);
		initProperty(org.archstudio.bna.things.swt.SWTScrollBarThing.MIN_KEY, 0);
		initProperty(org.archstudio.bna.things.swt.SWTScrollBarThing.TYPE_KEY, org.archstudio.bna.things.swt.SWTScrollBarThing.Type.HORIZONTAL);
		initProperty(org.archstudio.bna.things.swt.SWTScrollBarThing.VALUE_KEY, 50);
		super.initProperties();
	}

	public int getMax() {
		return get(org.archstudio.bna.things.swt.SWTScrollBarThing.MAX_KEY);
	}

	/*package*/ int getRawMax() {
		return getRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.MAX_KEY);
	}

	public void setMax(int max) {
		set(org.archstudio.bna.things.swt.SWTScrollBarThing.MAX_KEY, max);
	}

	/*package*/ int setRawMax(int max) {
		return setRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.MAX_KEY, max);
	}

	public int getMin() {
		return get(org.archstudio.bna.things.swt.SWTScrollBarThing.MIN_KEY);
	}

	/*package*/ int getRawMin() {
		return getRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.MIN_KEY);
	}

	public void setMin(int min) {
		set(org.archstudio.bna.things.swt.SWTScrollBarThing.MIN_KEY, min);
	}

	/*package*/ int setRawMin(int min) {
		return setRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.MIN_KEY, min);
	}

	public org.archstudio.bna.things.swt.SWTScrollBarThing.Type getType() {
		return get(org.archstudio.bna.things.swt.SWTScrollBarThing.TYPE_KEY);
	}

	/*package*/ org.archstudio.bna.things.swt.SWTScrollBarThing.Type getRawType() {
		return getRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.TYPE_KEY);
	}

	public void setType(org.archstudio.bna.things.swt.SWTScrollBarThing.Type type) {
		set(org.archstudio.bna.things.swt.SWTScrollBarThing.TYPE_KEY, type);
	}

	/*package*/ org.archstudio.bna.things.swt.SWTScrollBarThing.Type setRawType(org.archstudio.bna.things.swt.SWTScrollBarThing.Type type) {
		return setRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.TYPE_KEY, type);
	}

	public int getValue() {
		return get(org.archstudio.bna.things.swt.SWTScrollBarThing.VALUE_KEY);
	}

	/*package*/ int getRawValue() {
		return getRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.VALUE_KEY);
	}

	public void setValue(int value) {
		set(org.archstudio.bna.things.swt.SWTScrollBarThing.VALUE_KEY, value);
	}

	/*package*/ int setRawValue(int value) {
		return setRaw(org.archstudio.bna.things.swt.SWTScrollBarThing.VALUE_KEY, value);
	}

}
