package org.archstudio.bna.things.swt;

import org.archstudio.bna.IBNAView;
import org.archstudio.bna.ICoordinateMapper;
import org.archstudio.bna.IThingPeer;
import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.IThingRefKey;
import org.archstudio.bna.keys.ThingKey;
import org.archstudio.bna.keys.ThingRefKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.things.swt]/Thing[name=SWTText].
 */
 
@SuppressWarnings("all")
@NonNullByDefault
public abstract class SWTTextThingBase extends org.archstudio.bna.things.swt.AbstractControlThing
	implements org.archstudio.bna.IThing,
			org.archstudio.bna.facets.IHasMutableText {

	public SWTTextThingBase(@Nullable Object id) {
		super(id);
	}

	@Override
	public IThingPeer<? extends SWTTextThing> createPeer(IBNAView view, ICoordinateMapper cm) {
		return new SWTTextThingPeer<>((SWTTextThing)this, view, cm);
	}

	@Override
	protected void initProperties() {
		initProperty(org.archstudio.bna.facets.IHasText.TEXT_KEY, "Text");
		super.initProperties();
	}

	public java.lang.String getText() {
		return get(org.archstudio.bna.facets.IHasText.TEXT_KEY);
	}

	/*package*/ java.lang.String getRawText() {
		return getRaw(org.archstudio.bna.facets.IHasText.TEXT_KEY);
	}

	public void setText(java.lang.String text) {
		set(org.archstudio.bna.facets.IHasText.TEXT_KEY, text);
	}

	/*package*/ java.lang.String setRawText(java.lang.String text) {
		return setRaw(org.archstudio.bna.facets.IHasText.TEXT_KEY, text);
	}

}
