<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xadlcore_3_0"
    nsURI="http://www.archstudio.org/xadl3/schemas/xadlcore-3.0.xsd" nsPrefix="xadlcore_3_0">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;&#x9;xADL 3 Core Schema&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;&#x9;This schema defines the core elements for xADL 3 documents.&#xD;&#xA;&#x9;&#x9;&#x9;The schema is intentionally small, defining only a few elements&#xD;&#xA;&#x9;&#x9;&#x9;that are intended to be common across xADL descriptions and&#xD;&#xA;&#x9;&#x9;&#x9;extensions, regardless of domain.&#xD;&#xA;&#xD;&#xA;&#x9;&#x9;&#x9;Changelog:&#xD;&#xA;&#x9;&#x9;&#x9;  - 3.0.0:&#xD;&#xA;&#x9;&#x9;&#x9;    * Initial version&#xD;&#xA;&#x9;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value=""/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="name" value=":mixed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xmlns:prefix"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xsi:schemaLocation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelElement" upperBound="-2"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" volatile="true"
        transient="true" derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;This is a placeholder element for xADL top-level&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;elements (i.e., elements that are direct children&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;of the document root element.  Elements that&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;are intended to be top-level elements should be&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;in the topLevelElement substitutionGroup to&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;declare their intent to be used as top-level&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;elements.&#xD;&#xA;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="topLevelElement"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xADL" upperBound="-2" eType="#//XADLType"
        volatile="true" transient="true" derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;This is the root element for all xADL documents.  It&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;is a container element, so it can contain a number&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;of top-level xADL elements via the use of a&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;substitution group.&#xD;&#xA;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="xADL"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;This is an abstract base type for all extensions that&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;add content to an element.  In general, individual&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;types will create their own abstract Extension base&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;type (e.g., a type Foo will be accompanied by a&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;FooExtension base type that extends Extension)&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;and the type will include a list of zero or more&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;FooExtensions.&#xD;&#xA;&#x9;&#x9;&#x9;"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Extension"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleLink">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;This type is meant to describe elements that are&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;simple outbound links outside the current document&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;(internal links should use IDREFs). Elements of this &#xD;&#xA;&#x9;&#x9;&#x9;&#x9;type are simple-type XLinks that can use a simple&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;href to link to a document, or XPointer to&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;refer to an element within a document.&#xD;&#xA;&#x9;&#x9;&#x9;"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SimpleLink"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="href"/>
        <details key="namespace" value="http://www.w3.org/1999/xlink"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="simple" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="type"/>
        <details key="namespace" value="http://www.w3.org/1999/xlink"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XADLType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="xADL_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelElement" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;This is a placeholder element for xADL top-level&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;elements (i.e., elements that are direct children&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;of the document root element.  Elements that&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;are intended to be top-level elements should be&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;in the topLevelElement substitutionGroup to&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;declare their intent to be used as top-level&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;elements.&#xD;&#xA;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="topLevelElement"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
