package org.archstudio.bna.logics.mapping;

import org.archstudio.bna.IThing;
import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;

public interface IBNAMappingLogic<T extends IThing> {
	public static final IThingKey<IBNAMappingLogic<?>> MAPPING_KEY = ThingKey.create(IBNAMappingLogic.class);

	/**
	 * Applies defaults (e.g., color, font, etc.) to a thing generated by this logic.
	 *
	 * @param thing
	 *            The thing for which defaults should be applied.
	 */
	public void applyDefaults(T thing);
}
