package org.archstudio.bna.facets;

import org.eclipse.jdt.annotation.NonNullByDefault;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN. To modify, update the
 * thingdefinition extension at org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=RoundCorners].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableRoundCorners extends IHasRoundCorners {
	public void setRoundCorners(java.awt.Dimension roundCorners);
}