package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Endpoints].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableEndpoints extends IHasEndpoints {

	public static final String USER_MAY_MOVE_ENDPOINT_1 = "UserMayMoveEndpoint1";

	public static final String USER_MAY_MOVE_ENDPOINT_2 = "UserMayMoveEndpoint2";

	public static final String USER_MAY_RESTICK_ENDPOINT_1 = "UserMayRestickEndpoint1";

	public static final String USER_MAY_RESTICK_ENDPOINT_2 = "UserMayRestickEndpoint2";

	public void setEndpoint1(java.awt.geom.Point2D endpoint1);

	public void setEndpoint2(java.awt.geom.Point2D endpoint2);

}
