package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Flow].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableFlow extends IHasFlow {

	public static final String USER_MAY_EDIT_FLOW = "UserMayEditFlow";

	public void setFlow(org.archstudio.swtutils.constants.Flow flow);

}
