package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.IThingRefKey;
import org.archstudio.bna.keys.ThingKey;
import org.archstudio.bna.keys.ThingRefKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=InternalWorldPoint].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasInternalWorldPoint extends org.archstudio.bna.IThing {

	public static final IThingKey<java.awt.geom.Point2D> INTERNAL_POINT_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("internalPoint", IHasInternalWorldPoint.class), org.archstudio.bna.keys.ThingKey.point2D());

	public static final IThingRefKey<org.archstudio.bna.facets.IHasWorld> INTERNAL_WORLD_KEY = ThingRefKey.create(com.google.common.collect.Lists.newArrayList("internalWorld", IHasInternalWorldPoint.class));

	public java.awt.geom.Point2D getInternalPoint();

	public @Nullable org.archstudio.bna.facets.IHasWorld getInternalWorld(org.archstudio.bna.IBNAModel model);

}
