package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=LineData].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableLineData extends IHasLineData,
		org.archstudio.bna.facets.IHasMutableEdgeColor,
		org.archstudio.bna.facets.IHasMutableLineStyle,
		org.archstudio.bna.facets.IHasMutableLineWidth {

}
