package org.archstudio.bna.facets;

import org.eclipse.jdt.annotation.NonNullByDefault;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN. To modify, update the
 * thingdefinition extension at org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=LineStyle].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableLineStyle extends IHasLineStyle {

	public void setLineStyle(org.archstudio.swtutils.constants.LineStyle lineStyle);

}
