package org.archstudio.bna.facets;

import org.eclipse.jdt.annotation.NonNullByDefault;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN. To modify, update the
 * thingdefinition extension at org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=LocalInsets].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableLocalInsets extends IHasLocalInsets {

	public void setLocalInsets(java.awt.Insets localInsets);

}
