package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.IThingRefKey;
import org.archstudio.bna.keys.ThingKey;
import org.archstudio.bna.keys.ThingRefKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Endpoints].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasEndpoints extends org.archstudio.bna.IThing {

	public static final IThingKey<java.awt.geom.Point2D> ENDPOINT_1_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("endpoint1", IHasEndpoints.class), org.archstudio.bna.keys.ThingKey.point2D());

	public static final IThingKey<java.awt.geom.Point2D> ENDPOINT_2_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("endpoint2", IHasEndpoints.class), org.archstudio.bna.keys.ThingKey.point2D());

	public java.awt.geom.Point2D getEndpoint1();

	public java.awt.geom.Point2D getEndpoint2();

}
