package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.IThingRefKey;
import org.archstudio.bna.keys.ThingKey;
import org.archstudio.bna.keys.ThingRefKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Glow].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasGlow extends org.archstudio.bna.IThing {

	public static final IThingKey<java.lang.Double> GLOW_ALPHA_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("glowAlpha", IHasGlow.class));

	public static final IThingKey<org.eclipse.swt.graphics.RGB> GLOW_COLOR_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("glowColor", IHasGlow.class), true);

	public static final IThingKey<java.lang.Integer> GLOW_WIDTH_KEY = ThingKey.create(com.google.common.collect.Lists.newArrayList("glowWidth", IHasGlow.class));

	public double getGlowAlpha();

	public @Nullable org.eclipse.swt.graphics.RGB getGlowColor();

	public int getGlowWidth();

}
