package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Glow].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableGlow extends IHasGlow {

	public void setGlowAlpha(float glowAlpha);

	public void setGlowColor(@Nullable org.eclipse.swt.graphics.RGB glowColor);

	public void setGlowWidth(int glowWidth);

}
