package org.archstudio.bna.facets;

import org.eclipse.jdt.annotation.NonNullByDefault;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=ToolTip].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableToolTip extends IHasToolTip {

  public static final String USER_MAY_EDIT_TOOL_TIP = "UserMayEditToolTip";

  public void setToolTip(java.lang.String toolTip);

}
