package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.IThingRefKey;
import org.archstudio.bna.keys.ThingKey;
import org.archstudio.bna.keys.ThingRefKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=LineData].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasLineData extends org.archstudio.bna.IThing,
		org.archstudio.bna.facets.IHasEdgeColor,
		org.archstudio.bna.facets.IHasLineStyle,
		org.archstudio.bna.facets.IHasLineWidth {

}
