package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Color].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableColor extends IHasColor {

	public static final String USER_MAY_COPY_COLOR = "UserMayCopyColor";

	public static final String USER_MAY_EDIT_COLOR = "UserMayEditColor";

	public void setColor(@Nullable org.eclipse.swt.graphics.RGB color);

}
