package org.archstudio.bna.facets;

import org.archstudio.bna.keys.IThingKey;
import org.archstudio.bna.keys.ThingKey;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/*
 * DO NOT EDIT THIS FILE, it is automatically generated. ANY MODIFICATIONS WILL BE OVERWRITTEN.
 *
 * To modify, update the thingdefinition extension at
 * org.archstudio.bna/Package[name=org.archstudio.bna.facets]/Facet[name=Angle].
 */

@SuppressWarnings("all")
@NonNullByDefault
public interface IHasMutableAngle extends IHasAngle {

	public static final String USER_MAY_CHANGE_ANGLE = "UserMayChangeAngle";

	public void setAngle(int angle);

}
